config/routes.rb
Rails.application.routes.draw do
 
  root to:'pages#home'

  devise_for :users, controllers: {
    sessions:           "users/sessions",
    passwords:          "users/passwords",
    registrations:      "users/registrations",
    confirmations:      "users/confirmations",
    unlocks:            "users/unlocks"
  }

  devise_for :parents, controllers: {
    sessions:           "parents/sessions",
    passwords:          "parents/passwords",
    registrations:      "parents/registrations",
    confirmations:      "parents/confirmations",
    unlocks:            "parents/unlocks"
  }

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'login', to: 'pages#login'
  get 'sign_up', to: 'pages#sign_up'

  resource :user, only: [] do
    resource :company, except: [:index, :destroy], controller: 'users/companies' do 
      resources :camps, except: [:index], controller: 'users/companies/camps' 
    end
  end

  resources :camps, only: [:index, :show]
  
end

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
<h1>Home page</h1>

app/views/pages/login.html.erb
<h2>Parent login</h2>
<%= link_to "Login", parent_session_path %>

<h2>Company login</h2>
<%= link_to "Login", user_session_path %>

app/views/pages/sign_up.html.erb
<h2>Parent sign up</h2>
<%= link_to "Sign up", new_parent_registration_path %>

<h2>Company sign up</h2>
<%= link_to "Sign up", new_user_registration_path %>