config/routes.rb
Rails.application.routes.draw do
 
  root to:'pages#home'

  devise_for :users, controllers: {
    sessions:           "users/sessions",
    passwords:          "users/passwords",
    registrations:      "users/registrations",
    confirmations:      "users/confirmations",
    unlocks:            "users/unlocks"
  }

  devise_for :parents, controllers: {
    sessions:           "parents/sessions",
    passwords:          "parents/passwords",
    registrations:      "parents/registrations",
    confirmations:      "parents/confirmations",
    unlocks:            "parents/unlocks"
  }

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'login', to: 'pages#login'
  get 'sign_up', to: 'pages#sign_up'

  resource :user, only: [] do
    resource :company, except: [:index, :destroy], controller: 'users/companies' do 
      resources :camps, except: [:index], controller: 'users/companies/camps' 
    end
  end

  resources :camps, only: [:index, :show]
  
end

app/models/camp.rb
class Camp < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user, optional: true
  has_many :camps

  validates_presence_of :company_name, :about, :welfare, :childcare_voucher_info, :staff_info
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
	before_action :set_camp, only: [:show]

	def index
		@camps = Camp.all
	end

	def show
	end

	private
	def set_camp
		@camp = Camp.find(params[:id])
	end
end

app/controllers/users/companies/camps_controller.rb
module Users
	module Companies
		class CampsController < ApplicationController
			before_action :set_camp, only: [:show, :edit, :update, :destroy]
			
	    def show
	    end

	    def edit
	    end

	    def new
	    	@camp = current_user.company.camps.build
	    end

	    def create
	    	@camp = current_user.company.camps.build(camp_params)

	    	respond_to do |format|
	    		if @camp.save
	    			format.html { redirect_to user_company_path, notice: "You club is now live." }
	    		else
	    			format.html { render :new }
	    		end
	    	end
	    end

	    def update
	      respond_to do |format|
	        if @camp.update(camp_params)
	          format.html { redirect_to user_company_camp_path(@camp), notice: 'Your record sucessfully updated.'}
	        else 
	          format.html { render :edit }
	        end
	      end
	    end

	    def destroy
				@camp.destroy
		    respond_to do |format|
		      format.html { redirect_to user_company_path, notice: 'Record was removed.' }
		    end
			end

			private
			def camp_params
        params.require(:camp).permit(
        :name, 
        :camp_type, 
        :length, 
        :age_range,
        :activities,
        :capacity,
        :description,
        :postcode,
        :price,
        :coordinator,
        :things_to_bring
        )
	    end

			def set_camp
      	@camp = Camp.find(params[:id])
    	end
	
		end
	end
end

app/controllers/users/companies_controller.rb
module Users
  class CompaniesController < ApplicationController
    before_action :set_company, only: [:show, :edit, :update]
   
    def show
      @camps = current_user.company.camps.all
    end

    def new
      @company = current_user.build_company
    end

    def edit
    end

    def create
        @company = current_user.build_company(company_params)

        respond_to do |format|
            if @company.save
              format.html { redirect_to user_company_path, notice: 'Your company is now live.' }
            else 
              format.html { render :new }
            end
          end
    end

    def update
        respond_to do |format|
            if @company.update(company_params)
              format.html { redirect_to user_company_path, notice: 'Your record sucessfully updated.'}
            else 
              format.html { render :edit}
            end
          end
    end

    private
    def company_params
        params.require(:company).permit(
        :user_id, 
        :company_name, 
        :welfare, 
        :childcare_voucher_info,
        :staff_info,
        :about
        )
    end

    def set_company
        @company = current_user.company
    end

  end
end

app/views/users/companies/camps/edit.html.erb
<h3>Edit Camp Info</h3>

<%= form_for(@camp, url: user_company_camp_path(@camp)) do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :camp_type %>
		<%= f.text_field :camp_type %>
	</div>

	<div class="field">
		<%= f.label :length %>
		<%= f.number_field :length %>
	</div>

	<div class="field">
		<%= f.label :activities %>
		<%= f.text_field :activities %>
	</div>

	<div class="field">
		<%= f.label :capacity %>
		<%= f.text_field :capacity %>
	</div>

	<div class="field">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>

	<div class="field">
		<%= f.label :postcode %>
		<%= f.text_field :postcode %>
	</div>

	<div class="field">
		<%= f.label :price %>
		<%= f.number_field :price %>
	</div>

	<div class="field">
		<%= f.label :coordinator %>
		<%= f.text_field :coordinator %>
	</div>

	<div class="field">
		<%= f.label :things_to_bring %>
		<%= f.text_field :things_to_bring %>
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/companies/camps/new.html.erb
<h3>New Camp Info</h3>

<%= form_for(@camp, url: user_company_camps_path) do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :camp_type %>
		<%= f.text_field :camp_type %>
	</div>

	<div class="field">
		<%= f.label :length %>
		<%= f.number_field :length %>
	</div>

	<div class="field">
		<%= f.label :activities %>
		<%= f.text_field :activities %>
	</div>

	<div class="field">
		<%= f.label :capacity %>
		<%= f.text_field :capacity %>
	</div>

	<div class="field">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>

	<div class="field">
		<%= f.label :postcode %>
		<%= f.text_field :postcode %>
	</div>

	<div class="field">
		<%= f.label :price %>
		<%= f.number_field :price %>
	</div>

	<div class="field">
		<%= f.label :coordinator %>
		<%= f.text_field :coordinator %>
	</div>

	<div class="field">
		<%= f.label :things_to_bring %>
		<%= f.text_field :things_to_bring %>
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/companies/camps/show.html.erb
<h1><%= @camp.name %></h1>
<p><%= @camp.description %></p>
<p>Type: <%= @camp.camp_type %></p>
<p>Length: <%= @camp.length %> days</p>
<p>Price: £<%= @camp.price %></p>
<p>Things to bring: <%= @camp.things_to_bring %></p>
<p>Postcode: <%= @camp.postcode %></p>
<br>
<div><%= link_to "Edit", edit_user_company_camp_path %></div>
<div><%= link_to "Delete", user_company_camp_path, method: :delete, data: { confirm: 'Are you sure?' }  %></div>
<div><%= link_to "Back", user_company_path %></div>